const eventData = [
    {
      eventName: "Music of India",
      eventType: "Event",
      eventPrice: "500",
      timeSlots: ["11 AM", "2 PM", "7 PM"],
      location: "Bengaluru",
      eventImg: "https://cdn.exoticindia.com/books/music_musical_instruments_of_india_in_color_idl119.jpg",
    },
    {
      eventName: "Lior Suchord-Restoring Hope",
      eventType: "Event",
      eventPrice: "500",
      timeSlots: ["11 AM", "2 PM", "7 PM"],
      location: "Mumbai",
      eventImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgKOk0lEe4CYZUFOEStpwqp2oATDPHe85LEg&usqp=CAU",
    },
    {
      eventName: "Vijay Yadav - Live",
      eventType: "Event",
      eventPrice: "500",
      timeSlots: ["11 AM", "2 PM", "7 PM"],
      location: "Mumbai",
      eventImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYBSztFDcv_wkMr2DWVZ3elqbkK2L54Clt0w&usqp=CAU",
    },
    {
      eventName: "Mumbai - Film City Tour",
      eventType: "Activity",
      eventPrice: "500",
      timeSlots: ["11 AM", "2 PM", "7 PM"],
      location: "Mumbai",
      eventImg: "https://5.imimg.com/data5/SC/PB/GLADMIN-49352638/mumbai-filmcity-tours-500x500.png",
    },
    {
      eventName: "Imagica - Theam Park",
      eventType: "Activity",
      eventPrice: "500",
      timeSlots: ["11 AM", "2 PM", "7 PM"],
      location: "Mumbai",
      eventImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKWecxt5szTZRZjLmbnBu5gnhB82MEfL2Dqw&usqp=CAU",
    },
    {
      eventName: "Water Kingdom",
      eventType: "Activity",
      eventPrice: "500",
      timeSlots: ["11 AM", "2 PM", "7 PM"],
      location: "Bengaluru",
      eventImg: "https://pbs.twimg.com/media/EvDZ5K0UUAQCjOG.jpg",
    },
    {
      eventName: "Jab We Seperated",
      eventType: "Play",
      eventPrice: "500",
      timeSlots: ["11 AM", "2 PM", "7 PM"],
      location: "Mumbai",
      eventImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZiV4RTumyYjJuH1zUACiuHCYyHXfA7rXyhQ&usqp=CAU",
    },
    {
      eventName: "12 Angry Men",
      eventType: "Play",
      eventPrice: "500",
      timeSlots: ["11 AM", "2 PM", "7 PM"],
      location: "Mumbai",
      eventImg: "https://www.dramaticpublishing.com/media/catalog/product/cache/1/image/300x436/9df78eab33525d08d6e5fb8d27136e95/c/o/covertwelveangryment42.jpg",
    },
    {
      eventName: "Gandhi",
      eventType: "Play",
      eventPrice: "500",
      timeSlots: ["11 AM", "2 PM", "7 PM"],
      location: "Bengaluru",
      eventImg: "https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC/et00301094-thyahdhvdr-portrait.jpg",
    },
  ];

  export default eventData;